### ISSUE TITLE
How to sharing data between two app using intent and get result with onActivityResult ?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [googlesamples/android-ShareActionProvider#1]
Hi ! Please help me. How to sharing data between two app using intent and get result with onActivityResult ?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
